### ISSUE TITLE
REMME Core Readme suggestions

### ISSUE THREAD

**Issue by fedotovcorp** [Remmeauth/remme-core#154]
REMME Core
==========

|CircleCI| |Docker Stars| [![Join the chat at https://gitter.im/REMME-Tech](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/REMME-Tech)

What is REMME Core?
--------------------------------

:bookmark: [Quick intro from core solution architect](https://youtu.be/fw3591g0hiQ) 

OSS REMME Distributed Public Key Infrastructure (PKI d) protocol seeks to resolve: 
- cybersecurity issues
- safe IoT connectivity issues
- data integrity issues
- digital copyright protection issues
- transparency  issues 

:bookmark: [Read REMME use case for IoT](https://blog.aira.life/blockchain-as-refinery-for-industrial-iot-data-873b320a6ff0)

How to build on REMME Core
--------------------------------

1. You can store the public keys of SSL/TLS x.509 certificates on REMChain powered by REMME Core. 
2. Decide what kind of information will contain REMME digital certificate (multi-signature for example) basing on your needs.
3. Choose how you want to integrate REMME:

| Library  | Repository | Version | Download | 
| ------------- | ------------- | ------------- | ------------- | 
| REMME JS SDK   | [remme-client-js](https://github.com/Remmeauth/remme-client-js)| 0.5.2 | [![Downloads](https://camo.githubusercontent.com/538dcca1ff58dbb28a02ef2640906a8786c1f5f7/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f646d2f72656d6d652e737667)](https://github.com/Remmeauth/remme-client-js)  |
| REMME .NET SDK   | [remme-client-dotnet](https://github.com/Remmeauth/remme-client-dotnet) | 0.3.3 | [![Downloads](https://camo.githubusercontent.com/aa1a4960affdb2f94d1e7b22c1275d475ce634fc/68747470733a2f2f62616467652e667572792e696f2f6e752f52454d4d452e417574682e436c69656e742e737667)](https://badge.fury.io/nu/REMME.Auth.Client) |
| REMME Java SDK  | not available  | - | under development |
| REMME Python SDK   | not available  | - | under development |
| REMME OAuth | not available  | - | under development |
4. Use REMME Testnet to check your ideas.
5. Discuss your integration concept in REMME tech community or call for help if you need it.

Getting started
-----------------
**How to run a node**

The node was tested on Linux and macOS. Running on Windows may require
significant modification of startup scripts.

Currently it is not possible to connect your own node to the test network. All
nodes you will run will work on your own network.

You will need Docker and Docker Compose installed on your machine.

For an end-user
~~~~~~~~~~~~~~~

#. Download the latest release from `Releases`_ section
   (``<version_number>-release.zip``). Unpack it.
#. Start node: Open a terminal inside the unpacked folder and run
   ``./run.sh``.
#. You can now use our RPC API. By default it is started on
   http://localhost:8080. The API port can be changed in
   ``config/network-config.env`` file.

On the first run you will need to initialize the genesis block. To make
that just run ``./run.sh -g``. This will generate a new key pair and
genesis block.

Flags available for ``run.sh`` are:

- ``scripts/run.sh`` features a single entrypoint to run a project with the
   following flags:
  
  - ``-g`` to run a node in genesis mode
  - ``-b`` to run a node in background
  - ``-u`` to start a node (default flag)
  - ``-d`` to stop a node
  - ``-l`` to perform all of the above operations on log.io

For developers & contributors
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Clone this repository to your machine:
``git clone https://github.com/Remmeauth/remme-core.git``

When you have this repository cloned go the project directory and run

#. ``make build_dev`` (``make build`` for more compact but slower builds)
#. ``make run_genesis`` or ``make run`` if you are working on an existing chain.

Detailed instructions are available in `BUILD.md <BUILD.md>`_

**NOTE:** on further runs you might want to run ``make run`` to persist the
transaction created before. If you want to start with a clean chain, use ``make
run_genesis`` again.

You can run ``make test`` to run automated tests.

Building documentation
----------------------

Prerequesites for building the documentation are ``sphinx`` and
``sphinx_rtd_theme``. You can build the documentation with ``make docs``
command.

License
-------

REMME software and documentation are licensed under `Apache License Version 2.0
<LICENCE>`_.

.. _Releases: https://github.com/Remmeauth/remme-core/releases

.. |CircleCI| image:: https://img.shields.io/circleci/project/github/Remmeauth/remme-core.svg
   :target: https://circleci.com/gh/Remmeauth/remme-core
.. |Docker Stars| image:: https://img.shields.io/docker/stars/remme/remme-core.svg
   :target: https://hub.docker.com/r/remme/remme-core/

Useful resources
-------------------------

[REMME documentation](https://docs.remme.io/)
[REMME Testnet](https://blockexplorer.remme.io/)
[REMME Q&A](https://support.remme.io)
[REMME Tech Community in GITTER](https://gitter.im/REMME-Tech)

**Comment by Amruta-Ranade** [comment]
It's so much clearer now! Thank you! A few additional thoughts:

- I would still recommend adding a link to the explainer video (it's a really good video!)
- It might be helpful to add the "How to run a node" section as a Getting Started section right before the "Useful resources" section. (I parsed through the REMME documentation and couldn't find an easy way to get started, so it would be better to include the information in the readme)

**Comment by sergchernata** [comment]
I know this is aimed at developers, but there probably should be something to explain the benefits of a _distributed_ PKI. Preferably a list of 3-5 bullets.

Also, it would be useful if the items in "seeks to resolve" list were each linked to a blog post or something that gives specific examples of these issues.
